/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDashboard {
    }
    interface ProfileAvatar {
        "name": any;
        "size": string;
    }
    interface ProfileCard {
    }
    interface ProfileLevel {
        "username": string;
    }
    interface ProfileLogin {
    }
    interface UserChallenges {
        "xp2500Collected": boolean;
        "xp500Collected": boolean;
    }
}
declare global {
    interface HTMLAppDashboardElement extends Components.AppDashboard, HTMLStencilElement {
    }
    var HTMLAppDashboardElement: {
        prototype: HTMLAppDashboardElement;
        new (): HTMLAppDashboardElement;
    };
    interface HTMLProfileAvatarElement extends Components.ProfileAvatar, HTMLStencilElement {
    }
    var HTMLProfileAvatarElement: {
        prototype: HTMLProfileAvatarElement;
        new (): HTMLProfileAvatarElement;
    };
    interface HTMLProfileCardElement extends Components.ProfileCard, HTMLStencilElement {
    }
    var HTMLProfileCardElement: {
        prototype: HTMLProfileCardElement;
        new (): HTMLProfileCardElement;
    };
    interface HTMLProfileLevelElement extends Components.ProfileLevel, HTMLStencilElement {
    }
    var HTMLProfileLevelElement: {
        prototype: HTMLProfileLevelElement;
        new (): HTMLProfileLevelElement;
    };
    interface HTMLProfileLoginElement extends Components.ProfileLogin, HTMLStencilElement {
    }
    var HTMLProfileLoginElement: {
        prototype: HTMLProfileLoginElement;
        new (): HTMLProfileLoginElement;
    };
    interface HTMLUserChallengesElement extends Components.UserChallenges, HTMLStencilElement {
    }
    var HTMLUserChallengesElement: {
        prototype: HTMLUserChallengesElement;
        new (): HTMLUserChallengesElement;
    };
    interface HTMLElementTagNameMap {
        "app-dashboard": HTMLAppDashboardElement;
        "profile-avatar": HTMLProfileAvatarElement;
        "profile-card": HTMLProfileCardElement;
        "profile-level": HTMLProfileLevelElement;
        "profile-login": HTMLProfileLoginElement;
        "user-challenges": HTMLUserChallengesElement;
    }
}
declare namespace LocalJSX {
    interface AppDashboard {
    }
    interface ProfileAvatar {
        "name"?: any;
        "size"?: string;
    }
    interface ProfileCard {
    }
    interface ProfileLevel {
        "username"?: string;
    }
    interface ProfileLogin {
    }
    interface UserChallenges {
        "xp2500Collected"?: boolean;
        "xp500Collected"?: boolean;
    }
    interface IntrinsicElements {
        "app-dashboard": AppDashboard;
        "profile-avatar": ProfileAvatar;
        "profile-card": ProfileCard;
        "profile-level": ProfileLevel;
        "profile-login": ProfileLogin;
        "user-challenges": UserChallenges;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-dashboard": LocalJSX.AppDashboard & JSXBase.HTMLAttributes<HTMLAppDashboardElement>;
            "profile-avatar": LocalJSX.ProfileAvatar & JSXBase.HTMLAttributes<HTMLProfileAvatarElement>;
            "profile-card": LocalJSX.ProfileCard & JSXBase.HTMLAttributes<HTMLProfileCardElement>;
            "profile-level": LocalJSX.ProfileLevel & JSXBase.HTMLAttributes<HTMLProfileLevelElement>;
            "profile-login": LocalJSX.ProfileLogin & JSXBase.HTMLAttributes<HTMLProfileLoginElement>;
            "user-challenges": LocalJSX.UserChallenges & JSXBase.HTMLAttributes<HTMLUserChallengesElement>;
        }
    }
}
